name: JSON check

on:
  push:
    paths:
      - '**.json'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '2'
      - name: deletion-check
        uses: cloudsecurityalliance/gsd-tools/actions/deletion-check@main
      - name: json-check
        uses: cloudsecurityalliance/gsd-tools/actions/json-check@main
      - name: json-validation
        uses: raphaelahrens/gsd-tools/actions/json_validator@json_validator
